#include "config.hpp"

// Default values can be overridden at build time using PlatformIO build flags, e.g.:
// build_flags =
//   -DWIFI_SSID_VALUE=\"your-ssid\"
//   -DWIFI_PASSWORD_VALUE=\"your-password\"
//   -DNTFY_SERVER_VALUE=\"https://ntfy.sh\"
//   -DNTFY_TOPIC_VALUE=\"esp32-uptime\"
//   -DNTFY_ACCESS_TOKEN_VALUE=\"token\"
//   -DNTFY_USERNAME_VALUE=\"user\"
//   -DNTFY_PASSWORD_VALUE=\"pass\"
//   -DDISCORD_WEBHOOK_URL_VALUE=\"https://discord.com/api/webhooks/...\"
//   -DBOOT_NOTIFICATION_ENABLED_VALUE=true

#ifndef WIFI_SSID_VALUE
#define WIFI_SSID_VALUE "xxx"
#endif

#ifndef WIFI_PASSWORD_VALUE
#define WIFI_PASSWORD_VALUE "xxx"
#endif

#ifndef WEB_AUTH_USERNAME_VALUE
#define WEB_AUTH_USERNAME_VALUE ""
#endif

#ifndef WEB_AUTH_PASSWORD_VALUE
#define WEB_AUTH_PASSWORD_VALUE ""
#endif

#ifndef BLE_DEVICE_NAME_VALUE
#define BLE_DEVICE_NAME_VALUE "ESP32-Uptime"
#endif

#ifndef BLE_PEER_NAME_VALUE
#define BLE_PEER_NAME_VALUE "MeshCore-XXX"
#endif

#ifndef BLE_PAIRING_PIN_VALUE
#define BLE_PAIRING_PIN_VALUE 123456
#endif

#ifndef BLE_MESH_CHANNEL_NAME_VALUE
#define BLE_MESH_CHANNEL_NAME_VALUE "Alerts"
#endif

#ifndef BLE_MESH_ROOM_SERVER_ID_VALUE
#define BLE_MESH_ROOM_SERVER_ID_VALUE ""
#endif

#ifndef BLE_MESH_ROOM_SERVER_PASSWORD_VALUE
#define BLE_MESH_ROOM_SERVER_PASSWORD_VALUE ""
#endif

#ifndef NTFY_SERVER_VALUE
#define NTFY_SERVER_VALUE "https://ntfy.sh"
#endif

#ifndef NTFY_TOPIC_VALUE
#define NTFY_TOPIC_VALUE ""
#endif

#ifndef NTFY_ACCESS_TOKEN_VALUE
#define NTFY_ACCESS_TOKEN_VALUE ""
#endif

#ifndef NTFY_USERNAME_VALUE
#define NTFY_USERNAME_VALUE ""
#endif

#ifndef NTFY_PASSWORD_VALUE
#define NTFY_PASSWORD_VALUE ""
#endif

#ifndef DISCORD_WEBHOOK_URL_VALUE
#define DISCORD_WEBHOOK_URL_VALUE ""
#endif

#ifndef SMTP_SERVER_VALUE
#define SMTP_SERVER_VALUE ""
#endif

#ifndef SMTP_PORT_VALUE
#define SMTP_PORT_VALUE 587
#endif

#ifndef SMTP_USE_TLS_VALUE
#define SMTP_USE_TLS_VALUE true
#endif

#ifndef SMTP_USERNAME_VALUE
#define SMTP_USERNAME_VALUE ""
#endif

#ifndef SMTP_PASSWORD_VALUE
#define SMTP_PASSWORD_VALUE ""
#endif

#ifndef SMTP_FROM_ADDRESS_VALUE
#define SMTP_FROM_ADDRESS_VALUE ""
#endif

#ifndef SMTP_TO_ADDRESS_VALUE
#define SMTP_TO_ADDRESS_VALUE ""
#endif

#ifndef BOOT_NOTIFICATION_ENABLED_VALUE
#define BOOT_NOTIFICATION_ENABLED_VALUE true
#endif

#ifndef LED_ENABLED_VALUE
#define LED_ENABLED_VALUE true
#endif

#ifndef SCREEN_TIMEOUT_VALUE
#define SCREEN_TIMEOUT_VALUE 60
#endif

// LoRa radio configuration defaults (for boards with built-in SX1262)
#ifndef LORA_FREQUENCY_VALUE
#define LORA_FREQUENCY_VALUE 915.0
#endif

#ifndef LORA_BANDWIDTH_VALUE
#define LORA_BANDWIDTH_VALUE 250.0
#endif

#ifndef LORA_SPREADING_FACTOR_VALUE
#define LORA_SPREADING_FACTOR_VALUE 10
#endif

#ifndef LORA_CODING_RATE_VALUE
#define LORA_CODING_RATE_VALUE 5
#endif

#ifndef LORA_SYNC_WORD_VALUE
#define LORA_SYNC_WORD_VALUE 0x12
#endif

#ifndef LORA_TX_POWER_VALUE
#define LORA_TX_POWER_VALUE 22
#endif

const char* WIFI_SSID = WIFI_SSID_VALUE;
const char* WIFI_PASSWORD = WIFI_PASSWORD_VALUE;

const char* WEB_AUTH_USERNAME = WEB_AUTH_USERNAME_VALUE;
const char* WEB_AUTH_PASSWORD = WEB_AUTH_PASSWORD_VALUE;

const char* BLE_DEVICE_NAME = BLE_DEVICE_NAME_VALUE;
const char* BLE_PEER_NAME = BLE_PEER_NAME_VALUE;
const uint32_t BLE_PAIRING_PIN = BLE_PAIRING_PIN_VALUE;
const char* BLE_MESH_CHANNEL_NAME = BLE_MESH_CHANNEL_NAME_VALUE;
const char* BLE_MESH_ROOM_SERVER_ID = BLE_MESH_ROOM_SERVER_ID_VALUE;
const char* BLE_MESH_ROOM_SERVER_PASSWORD = BLE_MESH_ROOM_SERVER_PASSWORD_VALUE;

const char* NTFY_SERVER = NTFY_SERVER_VALUE;
const char* NTFY_TOPIC = NTFY_TOPIC_VALUE;
const char* NTFY_ACCESS_TOKEN = NTFY_ACCESS_TOKEN_VALUE;
const char* NTFY_USERNAME = NTFY_USERNAME_VALUE;
const char* NTFY_PASSWORD = NTFY_PASSWORD_VALUE;

const char* DISCORD_WEBHOOK_URL = DISCORD_WEBHOOK_URL_VALUE;

const char* SMTP_SERVER = SMTP_SERVER_VALUE;
const int SMTP_PORT = SMTP_PORT_VALUE;
const bool SMTP_USE_TLS = SMTP_USE_TLS_VALUE;
const char* SMTP_USERNAME = SMTP_USERNAME_VALUE;
const char* SMTP_PASSWORD = SMTP_PASSWORD_VALUE;
const char* SMTP_FROM_ADDRESS = SMTP_FROM_ADDRESS_VALUE;
const char* SMTP_TO_ADDRESS = SMTP_TO_ADDRESS_VALUE;

const bool BOOT_NOTIFICATION_ENABLED = BOOT_NOTIFICATION_ENABLED_VALUE;

const bool LED_ENABLED = LED_ENABLED_VALUE;

const int SCREEN_TIMEOUT = SCREEN_TIMEOUT_VALUE;

// LoRa radio configuration
const float LORA_FREQUENCY = LORA_FREQUENCY_VALUE;
const float LORA_BANDWIDTH = LORA_BANDWIDTH_VALUE;
const uint8_t LORA_SPREADING_FACTOR = LORA_SPREADING_FACTOR_VALUE;
const uint8_t LORA_CODING_RATE = LORA_CODING_RATE_VALUE;
const uint8_t LORA_SYNC_WORD = LORA_SYNC_WORD_VALUE;
const int8_t LORA_TX_POWER = LORA_TX_POWER_VALUE;
